[[themes]]
name = "Solarized Osaka"
[themes.palette]
background = "#002c38"
foreground = "#9eabac"
black = "#001419"
red = "#db302d"
green = "#849900"
yellow = "#b28500"
blue = "#268bd3"
magenta = "#d23681"
cyan = "#29a298"
white = "#001419"
bright_black = "#001419"
bright_red = "#f55350"
bright_green = "#849900"
bright_yellow = "#c94c16"
bright_blue = "#46acf5"
bright_magenta = "#f254a0"
bright_cyan = "#1a6397"
bright_white = "#839395"
